In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")
df.head(10)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
5,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes
6,1452-KIOVK,Male,0,No,Yes,22,Yes,Yes,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Credit card (automatic),89.10,1949.4,No
7,6713-OKOMC,Female,0,No,No,10,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,No,Mailed check,29.75,301.9,No
8,7892-POOKP,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes
9,6388-TABGU,Male,0,No,Yes,62,Yes,No,DSL,Yes,...,No,No,No,No,One year,No,Bank transfer (automatic),56.15,3487.95,No

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [4]:
df["Churn"].value_counts()
#data imbalance var 
df.duplicated().value_counts()
df["customerID"].duplicated().value_counts()
#duplicate customer veya veri yok 


#genel plan 
#veriler genelde object onları encode edicem 
#verileri column column ele alıcam  hepsine detaylı bakmaya çalışıcam
#prepocesingeden sonr alogistic regresoyn 
#en son metriclerle değerlendirme 



df["gender"].unique()


df_clean = df.copy()
df_clean = df_clean.drop(columns=["customerID"])

In [5]:
df_clean = pd.get_dummies(df_clean, columns=["gender"], drop_first=True)

In [6]:
df_clean["gender_Male"]

In [7]:
df_clean

,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,gender_Male
0,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,False
1,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No,True
2,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,True
3,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,True
4,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No,True
7039,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No,False
7040,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No,False
7041,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes,True
7042,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No,True

In [8]:
df_clean["gender_Male"]= df_clean["gender_Male"].astype(int)

In [9]:
df_clean["Partner"] = df_clean["Partner"].str.strip().map({"Yes": 1, "No": 0})

In [10]:
import numpy as np

obj_cols = df_clean.select_dtypes(include=["object"]).columns

for c in obj_cols:
    vals = set(df_clean[c].dropna().astype(str).str.strip().unique())
    if vals.issubset({"Yes", "No"}):
        df_clean[c] = df_clean[c].astype(str).str.strip().map({"Yes": 1, "No": 0})

In [ ]:
obj_cols = df_clean.select_dtypes(include=["object"]).columns
obj_cols

In [14]:
df_clean["OnlineSecurity"].unique()

array(['No', 'Yes'], dtype=object)

In [12]:
df_clean["OnlineSecurity"] = (
    df_clean["OnlineSecurity"].astype(str).str.replace("No internet service", "No")
)

In [13]:
df_clean["OnlineSecurity"].unique()

array(['No', 'Yes'], dtype=object)

In [16]:
df_clean["OnlineSecurity"] = df_clean["OnlineSecurity"].astype(str).str.strip().map({"Yes": 1, "No": 0})

In [19]:
df_clean["OnlineSecurity"].unique()

array([0, 1])

In [20]:
df_clean

,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,gender_Male
0,0,1,0,1,0,No phone service,DSL,0,Yes,No,No,No,No,Month-to-month,1,Electronic check,29.85,29.85,0,0
1,0,0,0,34,1,No,DSL,1,No,Yes,No,No,No,One year,0,Mailed check,56.95,1889.5,0,1
2,0,0,0,2,1,No,DSL,1,Yes,No,No,No,No,Month-to-month,1,Mailed check,53.85,108.15,1,1
3,0,0,0,45,0,No phone service,DSL,1,No,Yes,Yes,No,No,One year,0,Bank transfer (automatic),42.30,1840.75,0,1
4,0,0,0,2,1,No,Fiber optic,0,No,No,No,No,No,Month-to-month,1,Electronic check,70.70,151.65,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,1,1,24,1,Yes,DSL,1,No,Yes,Yes,Yes,Yes,One year,1,Mailed check,84.80,1990.5,0,1
7039,0,1,1,72,1,Yes,Fiber optic,0,Yes,Yes,No,Yes,Yes,One year,1,Credit card (automatic),103.20,7362.9,0,0
7040,0,1,1,11,0,No phone service,DSL,1,No,No,No,No,No,Month-to-month,1,Electronic check,29.60,346.45,0,0
7041,1,1,0,4,1,Yes,Fiber optic,0,No,No,No,No,No,Month-to-month,1,Mailed check,74.40,306.6,1,1
7042,0,0,0,66,1,No,Fiber optic,1,No,Yes,Yes,Yes,Yes,Two year,1,Bank transfer (automatic),105.65,6844.5,0,1